
build:
	go build -o bin/methodsample cmd/methodsample/methodsample.go
	go build -o bin/methodWithHierarchySample cmd/methodsample/methodWithHierarchySample.go
	go build -o bin/reportingapp cmd/reportingapp/reportingapp.go
	go build -o bin/samplemodule cmd/samplemodule/samplemodule.go

clean:
	rm -rf bin/*

